"""update user model with card number

Revision ID: 0f11a1ff71ca
Revises: 72e4c18b4c3b
Create Date: 2023-04-27 07:08:18.173599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f11a1ff71ca'
down_revision = '72e4c18b4c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###
