"""remove card number from user model

Revision ID: 551573ceb7e2
Revises: 0f11a1ff71ca
Create Date: 2023-04-27 23:25:09.001476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551573ceb7e2'
down_revision = '0f11a1ff71ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=16), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
