"""remove card number from purchase model

Revision ID: 72e4c18b4c3b
Revises: e53c2bf204b5
Create Date: 2023-04-27 07:07:17.473637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e4c18b4c3b'
down_revision = 'e53c2bf204b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(length=16), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
